# Generated by Django 3.2.8 on 2021-10-26 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=255, verbose_name='Название тикета')),
                ('status_ticket', models.CharField(choices=[('1', 'Нерешенный'), ('2', 'Решенный'), ('3', 'Замороженный')], default='1', max_length=1)),
                ('date_time', models.DateTimeField(verbose_name='Дата и время создания тикета')),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель тикета')),
                ('support_manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_support', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер службы поддержки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('date_t', models.DateTimeField(verbose_name='Текст сообщения')),
                ('author_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_support_chat.ticket', verbose_name='Тикет')),
            ],
        ),
    ]
