# Generated by Django 3.2.8 on 2021-10-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_support_chat', '0005_remove_ticket_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_support_chat.ticket', verbose_name='Тикет'),
        ),
    ]
